plugins:
  - serverless-express # <- like so

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  region: ap-northeast-1
  # environment:
  #   NODE_OPTIONS: --require lambda-wrapper
  # tracing: true
  tracing:
    apiGateway: true
    lambda: true
    
service: lambda-express

layers:  
  express:  
    path: lib
    name: serverless-${sls:stage}-express-layer

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'

functions:
  app:
    handler: handler.api 
    events: 
      - http:
          method: ANY   
          path: /{proxy+}
    layers:
      - !Ref ExpressLambdaLayer
      - arn:aws:lambda:ap-northeast-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-18-1:1
    tracing: Active
    environment:
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler